#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: x86-19.07
on:
  release:
    types: published
  push:
#    branches:
#      - master
    paths:
      - '.github/workflows/x86-19.07.yml'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: dev-19.07

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          df -h
      - name: 自定义插件
        run: |
           cd package/diy
           git clone https://github.com/jerrykuku/lua-maxminddb.git 
           git clone https://github.com/awesome-openwrt/microsocks.git
           git clone https://github.com/Leo-Jo/luci-app-vssr
           git clone https://github.com/Leo-Jo-My/my my
           git clone https://github.com/Leo-Jo/luci-app-koolproxyR.git
           git clone https://github.com/frainzy1477/luci-app-clash.git
           git clone https://github.com/vernesong/OpenClash.git
           rm    -rfv  my/openwrt-dnsforwarder
           rm    -rfv  my/openwrt-simple-obfs
           rm    -rfv  my/openwrt-v2ray-plugin
                      
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # ========================固件定制部分=======================
          #
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_LIBSODIUM_MINIMAL=y
          CONFIG_LUCI_LANG_en=y
          CONFIG_PACKAGE_ChinaDNS=y
          CONFIG_PACKAGE_UnblockNeteaseMusic=y
          CONFIG_PACKAGE_UnblockNeteaseMusicGo=y
          CONFIG_PACKAGE_adbyby=y
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_cifsd-tools=y
          CONFIG_PACKAGE_dnscrypt-proxy-full=y
          CONFIG_PACKAGE_dnsforwarder=y
          CONFIG_PACKAGE_glib2=y
          CONFIG_PACKAGE_gq-client=y
          CONFIG_PACKAGE_gq-server=y
          CONFIG_PACKAGE_ip-full=y         
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_iptables-mod-nat-extra=y
          CONFIG_PACKAGE_kcptun-client=y
          CONFIG_PACKAGE_kmod-crypto-ccm=y
          CONFIG_PACKAGE_kmod-crypto-cmac=y
          CONFIG_PACKAGE_kmod-crypto-ctr=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-iv=y
          CONFIG_PACKAGE_kmod-crypto-md4=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          CONFIG_PACKAGE_kmod-crypto-rng=y
          CONFIG_PACKAGE_kmod-crypto-seqiv=y
          CONFIG_PACKAGE_kmod-crypto-sha256=y
          CONFIG_PACKAGE_kmod-crypto-sha512=y
          CONFIG_PACKAGE_kmod-crypto-wq=y
          CONFIG_PACKAGE_kmod-fs-cifsd=y
          CONFIG_PACKAGE_kmod-ifb=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-nat-extra=y
          CONFIG_PACKAGE_kmod-ipt-raw=y
          CONFIG_PACKAGE_kmod-macvlan=y
          CONFIG_PACKAGE_kmod-sched-connmark=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-usb-ehci=y
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y
          CONFIG_PACKAGE_libattr=y
          CONFIG_PACKAGE_libbz2=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcares=y
          CONFIG_PACKAGE_libelf=y
          CONFIG_PACKAGE_libev=y
          CONFIG_PACKAGE_libffi=y
          CONFIG_PACKAGE_libhttp-parser=y
          CONFIG_PACKAGE_libmaxminddb=y
          CONFIG_PACKAGE_libnghttp2=y
          CONFIG_PACKAGE_libnl-core=y
          CONFIG_PACKAGE_libnl-genl=y
          CONFIG_PACKAGE_libsodium=y
          CONFIG_PACKAGE_libustream-openssl=y
          CONFIG_PACKAGE_lua-cjson=y
          CONFIG_PACKAGE_lua-maxminddb=y
          CONFIG_PACKAGE_luasocket=y
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-advanced-reboot=y
          CONFIG_PACKAGE_luci-app-cifsd=y
          CONFIG_PACKAGE_luci-app-clash=y
          CONFIG_PACKAGE_luci-app-filebrowser=y
          CONFIG_PACKAGE_luci-app-koolproxyR=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-netdata=y
          CONFIG_PACKAGE_luci-app-nps=y
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-qos=y
          CONFIG_PACKAGE_luci-app-smartdns=y
          CONFIG_PACKAGE_luci-app-ssr-libev-server=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          CONFIG_PACKAGE_luci-app-udpxy=y
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-app-vssr=y
          CONFIG_PACKAGE_luci-i18n-adbyby-plus-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-base-en=y          
          CONFIG_PACKAGE_luci-i18n-cifsd-en=y
          CONFIG_PACKAGE_luci-i18n-cifsd-zh-cn=y        
          CONFIG_PACKAGE_luci-i18n-filebrowser-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-firewall-en=y         
          CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y         
          CONFIG_PACKAGE_luci-i18n-mwan3helper-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-netdata-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-qos-en=y
          CONFIG_PACKAGE_luci-i18n-qos-zh-cn=y         
          CONFIG_PACKAGE_luci-i18n-samba-en=y          
          CONFIG_PACKAGE_luci-i18n-smartdns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ssr-libev-server-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-unblockmusic-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wol-en=y          
          CONFIG_PACKAGE_mwan3=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_netdata=y
          CONFIG_PACKAGE_node=y
          CONFIG_PACKAGE_npc=y
          CONFIG_PACKAGE_privoxy=y
          CONFIG_PACKAGE_python3-base=y
          CONFIG_PACKAGE_python3-light=y
          CONFIG_PACKAGE_python3-maxminddb=y
          CONFIG_PACKAGE_qos-scripts=y
          CONFIG_PACKAGE_screen=y
          CONFIG_PACKAGE_shadowsocks-libev-config=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-server=y
          CONFIG_PACKAGE_shadowsocksr-libev-server=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_simple-obfs=y
          CONFIG_PACKAGE_simple-obfs-server=y
          CONFIG_PACKAGE_smartdns=y
          CONFIG_PACKAGE_tc=y
          CONFIG_PACKAGE_tree=y
          CONFIG_PACKAGE_udp2raw-tunnel=y
          CONFIG_PACKAGE_udpspeeder=y
          CONFIG_PACKAGE_udpxy=y
          CONFIG_PACKAGE_v2ray-plugin=y
          CONFIG_PACKAGE_vim-fuller=y
          # CONFIG_PACKAGE_rp-pppoe-common is not set
          # CONFIG_PACKAGE_rp-pppoe-relay is not set
          # CONFIG_PACKAGE_rp-pppoe-server is not set
          # CONFIG_PACKAGE_ppp is not set  
          # CONFIG_DEFAULT_luci-app-pppoe-relay is not set 
          # CONFIG_DEFAULT_luci-app-pppoe-server is not set  
          # CONFIG_PACKAGE_ppp-mod-pppoe is not set   
          # CONFIG_DEFAULT_ppp is not set    
          # CONFIG_DEFAULT_ppp-mod-pppoe is not set  
          # CONFIG_PACKAGE_kmod-ppp is not set   
          # CONFIG_PACKAGE_kmod-mppe is not set          
          # CONFIG_PACKAGE_kmod-pppoe is not set    
          # CONFIG_PACKAGE_kmod-pppox is not set 
          # CONFIG_PACKAGE_ip-tiny is not set
          # CONFIG_LUCI_LANG_zh-tw is not set
          # CONFIG_PACKAGE_luci-i18n-base-zh-tw is not set
          # CONFIG_PACKAGE_luci-i18n-ddns-zh-tw is not set
          # CONFIG_PACKAGE_luci-i18n-firewall-zh-tw is not set
          # CONFIG_PACKAGE_luci-i18n-mwan3-zh-tw is not set
          # CONFIG_PACKAGE_luci-i18n-qos-zh-tw is not set
          # CONFIG_PACKAGE_luci-i18n-samba-zh-tw is not set
          # CONFIG_PACKAGE_luci-i18n-wol-zh-tw is not set
          EOF
          # 
          # ========================固件定制部分结束========================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h
      - name: Compile firmware
        run: |
          make -j$(nproc) || make  V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt18.06 firmware
          path: ./bin/targets/
          
      - name: Upload  IPK
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt18.06 x86 IPK
          path: ./bin/packages/
